--
-- PostgreSQL database dump
--

-- Dumped from database version 14.1
-- Dumped by pg_dump version 14.2

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

--
-- Name: public; Type: SCHEMA; Schema: -; Owner: postgres
--

CREATE SCHEMA public;


ALTER SCHEMA public OWNER TO postgres;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- Name: anchor; Type: TABLE; Schema: public; Owner: supabase_admin
--

CREATE TABLE public.anchor (
    uuid uuid DEFAULT extensions.uuid_generate_v4() NOT NULL,
    created_at timestamp with time zone DEFAULT now(),
    deployment text,
    anchor_id integer,
    is_online boolean,
    location json,
    "networkID" text
);


ALTER TABLE public.anchor OWNER TO supabase_admin;

--
-- Name: core_config; Type: TABLE; Schema: public; Owner: supabase_admin
--

CREATE TABLE public.core_config (
    id bigint NOT NULL,
    created_at timestamp with time zone DEFAULT now()
);


ALTER TABLE public.core_config OWNER TO supabase_admin;

--
-- Name: core_config_id_seq; Type: SEQUENCE; Schema: public; Owner: supabase_admin
--

ALTER TABLE public.core_config ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.core_config_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: distance_reading; Type: TABLE; Schema: public; Owner: supabase_admin
--

CREATE TABLE public.distance_reading (
    id bigint NOT NULL,
    created_at timestamp with time zone DEFAULT now(),
    location json,
    node bigint,
    anchor integer[],
    crc_identification bigint
);


ALTER TABLE public.distance_reading OWNER TO supabase_admin;

--
-- Name: distance_reading_id_seq; Type: SEQUENCE; Schema: public; Owner: supabase_admin
--

ALTER TABLE public.distance_reading ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.distance_reading_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: node; Type: TABLE; Schema: public; Owner: supabase_admin
--

CREATE TABLE public.node (
    id bigint NOT NULL,
    created_at timestamp with time zone DEFAULT now(),
    title text,
    description text,
    online boolean
);


ALTER TABLE public.node OWNER TO supabase_admin;

--
-- Name: node_id_seq; Type: SEQUENCE; Schema: public; Owner: supabase_admin
--

ALTER TABLE public.node ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.node_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: core_config core_config_pkey; Type: CONSTRAINT; Schema: public; Owner: supabase_admin
--

ALTER TABLE ONLY public.core_config
    ADD CONSTRAINT core_config_pkey PRIMARY KEY (id);


--
-- Name: distance_reading distance_reading_pkey; Type: CONSTRAINT; Schema: public; Owner: supabase_admin
--

ALTER TABLE ONLY public.distance_reading
    ADD CONSTRAINT distance_reading_pkey PRIMARY KEY (id);


--
-- Name: anchor node_pkey; Type: CONSTRAINT; Schema: public; Owner: supabase_admin
--

ALTER TABLE ONLY public.anchor
    ADD CONSTRAINT node_pkey PRIMARY KEY (uuid);


--
-- Name: node node_pkey1; Type: CONSTRAINT; Schema: public; Owner: supabase_admin
--

ALTER TABLE ONLY public.node
    ADD CONSTRAINT node_pkey1 PRIMARY KEY (id);


--
-- Name: distance_reading distance_reading_node_fkey; Type: FK CONSTRAINT; Schema: public; Owner: supabase_admin
--

ALTER TABLE ONLY public.distance_reading
    ADD CONSTRAINT distance_reading_node_fkey FOREIGN KEY (node) REFERENCES public.node(id);


--
-- Name: anchor Enable access to all users; Type: POLICY; Schema: public; Owner: supabase_admin
--

CREATE POLICY "Enable access to all users" ON public.anchor FOR SELECT USING (true);


--
-- Name: distance_reading Enable access to all users; Type: POLICY; Schema: public; Owner: supabase_admin
--

CREATE POLICY "Enable access to all users" ON public.distance_reading FOR SELECT USING (true);


--
-- Name: anchor; Type: ROW SECURITY; Schema: public; Owner: supabase_admin
--

ALTER TABLE public.anchor ENABLE ROW LEVEL SECURITY;

--
-- Name: distance_reading; Type: ROW SECURITY; Schema: public; Owner: supabase_admin
--

ALTER TABLE public.distance_reading ENABLE ROW LEVEL SECURITY;

--
-- Name: SCHEMA public; Type: ACL; Schema: -; Owner: postgres
--

GRANT USAGE ON SCHEMA public TO anon;
GRANT USAGE ON SCHEMA public TO authenticated;
GRANT USAGE ON SCHEMA public TO service_role;


--
-- Name: TABLE anchor; Type: ACL; Schema: public; Owner: supabase_admin
--

GRANT ALL ON TABLE public.anchor TO postgres;
GRANT ALL ON TABLE public.anchor TO anon;
GRANT ALL ON TABLE public.anchor TO authenticated;
GRANT ALL ON TABLE public.anchor TO service_role;


--
-- Name: TABLE core_config; Type: ACL; Schema: public; Owner: supabase_admin
--

GRANT ALL ON TABLE public.core_config TO postgres;
GRANT ALL ON TABLE public.core_config TO anon;
GRANT ALL ON TABLE public.core_config TO authenticated;
GRANT ALL ON TABLE public.core_config TO service_role;


--
-- Name: SEQUENCE core_config_id_seq; Type: ACL; Schema: public; Owner: supabase_admin
--

GRANT ALL ON SEQUENCE public.core_config_id_seq TO postgres;
GRANT ALL ON SEQUENCE public.core_config_id_seq TO anon;
GRANT ALL ON SEQUENCE public.core_config_id_seq TO authenticated;
GRANT ALL ON SEQUENCE public.core_config_id_seq TO service_role;


--
-- Name: TABLE distance_reading; Type: ACL; Schema: public; Owner: supabase_admin
--

GRANT ALL ON TABLE public.distance_reading TO postgres;
GRANT ALL ON TABLE public.distance_reading TO anon;
GRANT ALL ON TABLE public.distance_reading TO authenticated;
GRANT ALL ON TABLE public.distance_reading TO service_role;


--
-- Name: SEQUENCE distance_reading_id_seq; Type: ACL; Schema: public; Owner: supabase_admin
--

GRANT ALL ON SEQUENCE public.distance_reading_id_seq TO postgres;
GRANT ALL ON SEQUENCE public.distance_reading_id_seq TO anon;
GRANT ALL ON SEQUENCE public.distance_reading_id_seq TO authenticated;
GRANT ALL ON SEQUENCE public.distance_reading_id_seq TO service_role;


--
-- Name: TABLE node; Type: ACL; Schema: public; Owner: supabase_admin
--

GRANT ALL ON TABLE public.node TO postgres;
GRANT ALL ON TABLE public.node TO anon;
GRANT ALL ON TABLE public.node TO authenticated;
GRANT ALL ON TABLE public.node TO service_role;


--
-- Name: SEQUENCE node_id_seq; Type: ACL; Schema: public; Owner: supabase_admin
--

GRANT ALL ON SEQUENCE public.node_id_seq TO postgres;
GRANT ALL ON SEQUENCE public.node_id_seq TO anon;
GRANT ALL ON SEQUENCE public.node_id_seq TO authenticated;
GRANT ALL ON SEQUENCE public.node_id_seq TO service_role;


--
-- Name: DEFAULT PRIVILEGES FOR SEQUENCES; Type: DEFAULT ACL; Schema: public; Owner: postgres
--

ALTER DEFAULT PRIVILEGES FOR ROLE postgres IN SCHEMA public GRANT ALL ON SEQUENCES  TO postgres;
ALTER DEFAULT PRIVILEGES FOR ROLE postgres IN SCHEMA public GRANT ALL ON SEQUENCES  TO anon;
ALTER DEFAULT PRIVILEGES FOR ROLE postgres IN SCHEMA public GRANT ALL ON SEQUENCES  TO authenticated;
ALTER DEFAULT PRIVILEGES FOR ROLE postgres IN SCHEMA public GRANT ALL ON SEQUENCES  TO service_role;


--
-- Name: DEFAULT PRIVILEGES FOR SEQUENCES; Type: DEFAULT ACL; Schema: public; Owner: supabase_admin
--

ALTER DEFAULT PRIVILEGES FOR ROLE supabase_admin IN SCHEMA public GRANT ALL ON SEQUENCES  TO postgres;
ALTER DEFAULT PRIVILEGES FOR ROLE supabase_admin IN SCHEMA public GRANT ALL ON SEQUENCES  TO anon;
ALTER DEFAULT PRIVILEGES FOR ROLE supabase_admin IN SCHEMA public GRANT ALL ON SEQUENCES  TO authenticated;
ALTER DEFAULT PRIVILEGES FOR ROLE supabase_admin IN SCHEMA public GRANT ALL ON SEQUENCES  TO service_role;


--
-- Name: DEFAULT PRIVILEGES FOR FUNCTIONS; Type: DEFAULT ACL; Schema: public; Owner: postgres
--

ALTER DEFAULT PRIVILEGES FOR ROLE postgres IN SCHEMA public GRANT ALL ON FUNCTIONS  TO postgres;
ALTER DEFAULT PRIVILEGES FOR ROLE postgres IN SCHEMA public GRANT ALL ON FUNCTIONS  TO anon;
ALTER DEFAULT PRIVILEGES FOR ROLE postgres IN SCHEMA public GRANT ALL ON FUNCTIONS  TO authenticated;
ALTER DEFAULT PRIVILEGES FOR ROLE postgres IN SCHEMA public GRANT ALL ON FUNCTIONS  TO service_role;


--
-- Name: DEFAULT PRIVILEGES FOR FUNCTIONS; Type: DEFAULT ACL; Schema: public; Owner: supabase_admin
--

ALTER DEFAULT PRIVILEGES FOR ROLE supabase_admin IN SCHEMA public GRANT ALL ON FUNCTIONS  TO postgres;
ALTER DEFAULT PRIVILEGES FOR ROLE supabase_admin IN SCHEMA public GRANT ALL ON FUNCTIONS  TO anon;
ALTER DEFAULT PRIVILEGES FOR ROLE supabase_admin IN SCHEMA public GRANT ALL ON FUNCTIONS  TO authenticated;
ALTER DEFAULT PRIVILEGES FOR ROLE supabase_admin IN SCHEMA public GRANT ALL ON FUNCTIONS  TO service_role;


--
-- Name: DEFAULT PRIVILEGES FOR TABLES; Type: DEFAULT ACL; Schema: public; Owner: postgres
--

ALTER DEFAULT PRIVILEGES FOR ROLE postgres IN SCHEMA public GRANT ALL ON TABLES  TO postgres;
ALTER DEFAULT PRIVILEGES FOR ROLE postgres IN SCHEMA public GRANT ALL ON TABLES  TO anon;
ALTER DEFAULT PRIVILEGES FOR ROLE postgres IN SCHEMA public GRANT ALL ON TABLES  TO authenticated;
ALTER DEFAULT PRIVILEGES FOR ROLE postgres IN SCHEMA public GRANT ALL ON TABLES  TO service_role;


--
-- Name: DEFAULT PRIVILEGES FOR TABLES; Type: DEFAULT ACL; Schema: public; Owner: supabase_admin
--

ALTER DEFAULT PRIVILEGES FOR ROLE supabase_admin IN SCHEMA public GRANT ALL ON TABLES  TO postgres;
ALTER DEFAULT PRIVILEGES FOR ROLE supabase_admin IN SCHEMA public GRANT ALL ON TABLES  TO anon;
ALTER DEFAULT PRIVILEGES FOR ROLE supabase_admin IN SCHEMA public GRANT ALL ON TABLES  TO authenticated;
ALTER DEFAULT PRIVILEGES FOR ROLE supabase_admin IN SCHEMA public GRANT ALL ON TABLES  TO service_role;


--
-- PostgreSQL database dump complete
--

